version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  app:
    build: ./split_audio_app
    restart: on-failure
    command: gunicorn app:app --bind 0:5000 --timeout 180
    expose:
      - 5000
    depends_on:
      - db
      - rabbitmq

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 5050:80
    depends_on:
      - app
      - rabbitmq
      - db


volumes:
  postgres_data:
  rabbitmq: