# Конфигурация ядра приложения
SECRET_KEY: d5pb8c4facbd46638d0dc4e751e3d67d
DEBUG: True
HOST: 0.0.0.0
PORT: 5050

# Конфигурация БД
db:
  engine: postgresql
  host: db
  port: 5432
  name: postgres
  user: postgres
  pass: postgres

# Конфигурация RMQ
rmq:
  host: rabbitmq
  port: 5672
  user: guest
  pass: guest
  vhost: "%2F"

# Конфигурация очередей RMQ
queues:
  tasks: tasks
  results: results

# Общие настройки приложения
common:
  # Количество тредов с консьюмером RabbitMQ
  consumer_threads: 2

# Конфигурация S3 хранилища
s3:
  endpoint: https://storage.yandexcloud.net
  bucket: your-bucket
  aws_server_public_key: your_public_key
  aws_server_secret_key: your_secret_key

audio:
  # Поддерживаемые расширения аудиофайлов
  supported_extensions:
    - aac
    - mid
    - mp3
    - m4a
    - ogg
    - flac
    - wav
    - amr
    - aiff
